# Definição de build para a imagem do Spring boot
FROM openjdk:17-jdk-alpine
ARG JAR_FILE=target/*.jar
VOLUME /tmp
COPY ./target/jupiterback-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]

FROM mysql
ENV MYSQL_ROOT_HOST=% \
    MYSQL_ROOT_PASSWORD=123
COPY init.sql /docker-entrypoint-initdb.d/1-init.sql
