# Use root/example as user/password credentials
version: '3.1'
services:
  JP_mysql:
    container_name: JP_mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command:
      --default-authentication-plugin=mysql_native_password
      #--init-file /docker-entrypoint-initdb.d/1-init.sql
    restart: always
    environment:
      DATABASE_HOST: JP_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQLDB_ROOT_DATABASE}
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
networks:
  database:
    external: true