server:
  port: 8081
spring:
  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
        sort-parameter: ordem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://192.168.100.21:3306/db_jupiterdsv01?useSSL=false"
    username: root
    password: 123
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  flyway:
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
      temp:
        use_jdbc_metadata_defaults: false
  sql:
    init:
      mode: always