# Use root/example as user/password credentials
version: '3.5'
services:
  ubuntu:
    container_name: ubuntu
    image: ubuntu
    tty: true
    stdin_open: true
    build:
      context: .
    networks:
      - spring-boot-mysql-network
    ports:
      - "3307:3307"
networks:
  spring-boot-mysql-network:
    external: true
    name: mars
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.100.0/24
         gateway: 192.168.100.1
         aux_addresses:
          ubuntu: 192.168.100.42