version: “3.9”

services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - int-bridge

  jupterapp:
    image: aluradocker/alura-books:1.0
    containter_name: alurabooks
    networks:
      - int-bridge
    ports:
      - 1000:1000

networks:
  int-bridge:
    driver: bridge
